

pandas.errors.InvalidComparison#


exception pandas.errors.InvalidComparison[source]#
Exception is raised by _validate_comparison_value to indicate an invalid comparison.
Notes
This is an internal error.


