

pandas.errors.LossySetitemError#


exception pandas.errors.LossySetitemError[source]#
Raised when trying to do a __setitem__ on an np.ndarray that is not lossless.
Notes
This is an internal error.


